export type TipoMovimento =
  | 'ENTRADA'
  | 'SAIDA'
  | 'AJUSTE_POSITIVO'
  | 'AJUSTE_NEGATIVO'
  | 'TRANSFERENCIA_SAIDA'
  | 'TRANSFERENCIA_ENTRADA'
  | 'PERDA'
  | 'PRODUCAO_CONSUMO'
  | 'PRODUCAO_GERACAO';
